### ISSUE TITLE
Node | Ruby SMM Panel Script – [Child + Affiliate + Refill]

### ISSUE THREAD

**Issue by smmpanelscript** [smmpanelscript/Ruby-smm-panel-script#1]
[### **Node | Ruby SMM Panel Script – [Child + Affiliate + Refill]**
](https://smmpanelscript.store/product/node-ruby-smm-panel-script)
Allows you to sell your Social Media Marketing Services with an easy to use panel. You can provide quality and cheap SMM Services to your customers, they can buy all packages or services like Facebook likes, Instagram followers, Twitter followers, Youtube Viewers and many more using your the panel. You can create as many as services & packages according to your expertise, this is a completely dynamic panel.

**Features:**

Mobile responsive UI
Child Panel [ Order System ]
Manual Refill
Affiliate Module
Easy to install and use
Payment gateway:  Paytm Auto, PayTm QR, Paypal, Stripe, and Manual payment methods are out of the box ready for use
Subscribers
User Mail Logs
User Activity Logs
Banned IP Address List
Multi API Requirement parameters Type
Place orders
Place Mass Orders
Add unlimited services
Add unlimited categories
Enable API
Automate fetch API
Multi API Providers (With the same API required parameters)
Multi services (Default, Auto Like, Custom comments, Comment Likes, Mentions with Hashtags, Mentions User Followers, Mentions Media Likers, Subscriptions, Package etc
Drip-feed feature
Currency converter feature
Sync services button with API providers
Bulk add all services from API provider and set price percentage increase
Custom rate per each user (Set percentage rate for Resellers)
Users and Admin dashboard
View User feature from admin account
Support Maintenance Mode
Support systems
Faqs systems
Tickets systems: Ticket messages timeline between user and admin
Payment gateway: Paypal, Stripe, 2Checkout and Manual payment methods are out of the box ready for use
User Add Funds in panel / Admin can also add funds to user accounts
User management
Secure Password Hashing
User registration and login system
Email notifications (email verification, welcome, new user notification, order notification, ticket reply, reset password and payment email)
News/Announcement Timeline system
Easy to install to edit the Email template
PHP mail and SMTP Configuration
Order management
Order the service through API without beginning
SEO optimization for meta tags, descriptions, keywords, etc
Website setting for icon, logo, etc
Automatic timezone
Embed code feature (Javascript code)
Multilingual ready
Basic statistics
Google ReCaptcha for sign up, forgot password page
Dynamic Pre-built pages for FAQs, Terms and Privacy page etc.
And many other exciting features

**Server Requirements:**

PHP 7.0~ 7.3
MySQL 5.1+
mod_rewrite Apache
MySQLi PHP Extension
PDO PHP Extension
cURL PHP Extension
OpenSSL PHP Extension
MBString PHP Extension
GD PHP Extension
Zip PHP Extension
allow_url_fopen enabled

**Comment by Makwansabir** [comment]
Hey
